---
- name: Add the Microsoft apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc 
    state: present

- name: Add Microsoft Visual Studio Code apt repository
  apt_repository: 
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" 
    state: present 
    filename: 'vscode'

- name: Update repositories cache and install Visual Studio Code package
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - code
    - libxss1
    - libasound2
    