---
- name: Ensure that ~/.gnupg directory exists
  file:
    path: '/{{root_user}}/.gnupg'
    state: 'directory'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
    mode: '0700'

# Mirrors. You can change counry or add another one to cover you needs (..country=DE&..)
- name: Download pacman mirror list
  get_url:
    url: "https://www.archlinux.org/mirrorlist/?country=RU&protocol=http&ip_version=4&ip_version=6&use_mirror_status=on"
    dest: "/etc/pacman.d/mirrorlist"
    force: "yes"

# Enable mirrors
- name: "Uncomment `#Server` in pacman mirror list"
  replace:
    dest: "/etc/pacman.d/mirrorlist"
    regexp: '^#Server'
    replace: 'Server'

# Pacman colors
- name: "Uncomment pacman colors"
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    regexp: "^Color"
    insertafter: "^#Color"
    line: "Color"

# Enable multilib
- name: Add multilib repo
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: Add multilib mirror
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    regexp: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"

- name: Install software on Arch Linux
  pacman: name={{ item }} state=latest update_cache=yes
  when: need_main_software_setup == "yes"
  with_items:
    - "{{ packages }}"
