---
- name: Remove old packages
  apt: name={{ item }} state=absent
  loop: "{{ del_packages }}"

- name: Update apt cache
  apt: update_cache=yes
  changed_when: False

- name: Upgrade packages
  apt: upgrade=dist

- name: Install packages
  apt: name={{ item }} state=present
  loop: "{{ apt_packages }}"

- name: Install pip
  easy_install: name=pip

- name: Install pip packages
  pip: name={{ item }} state=latest
  loop: "{{ pip_packages }}"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest