---
- name: Am I running on Mac OS X?
  fail:
    msg: Target host is not running Mac OS X
  when: ansible_distribution != 'MacOSX'

- name: Remove existing Command Line Tools installation
  file:
    path: '{{ xcode.clt_path }}'
    state: absent
  when: xcode.force_install
  become: yes

- name: Check that the Command Line Tools path is present
  stat:
    path: '{{ xcode.clt_path }}'
  register: clt

- name: Is the C++ compiler useable?
  command: g++ --version
  register: compiler
  check_mode: no
  ignore_errors: true
  changed_when: false

- name: Check the Command Line Tools package metadata
  command: pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
  register: pkg_info
  check_mode: no
  ignore_errors: true
  changed_when: false

- name: Prepare to install Command Line Tools
  file:
    path: /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    state: touch
  when: pkg_info.rc != 0 or compiler.rc != 0 or not clt.stat.exists

- name: Check for Command Line Tools in Software Update list
  shell: >
    set -o pipefail;
    softwareupdate -l |
    grep -B 1 -E 'Command Line Tools' |
    awk -F'*' '/^ +\*/ {print $2}' |
    sed 's/^ *//' |
    grep -iE '[0-9|.]' |
    sort |
    tail -n1
  args:
    executable: /bin/bash
  register: su_list
  when: pkg_info.rc != 0 or compiler.rc != 0 or not clt.stat.exists
  changed_when: false
  failed_when: su_list.rc != 0 or su_list.stdout|length == 0

- name: Install Command Line Tools
  command: softwareupdate -i '{{ su_list.stdout }}'
  when: pkg_info.rc != 0 or compiler.rc != 0 or not clt.stat.exists
  notify:
    - XCode Cleanup
  register: su_result
  failed_when: >-
    su_result.rc != 0 or
    'Error installing updates.' in su_result.stdout

# - name: Accepting XCode License
#   command: xcodebuild -license accept
#   become: yes
